server:
  port: 8985
spring:
  application:
    name: products-app
  datasource:
    url: jdbc:mysql://localhost:3306/products-app
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create